name: field-maps-scripts
channels:
  - esri
  - conda-forge
dependencies:
  - arcgis>=2.4.0
  - arcgis-mapping>=4.30.0
  - cairo>=1.16.0
  - cartopy>=0.18.0
  - gdk-pixbuf>=2.42.2
  - jinja2>=2.11.2
  - pango>=1.42.4
  - pillow>=11.0.0
  - pip>=24.3.1
  - python>=3.10.15
  - flake8>=3.8.3
  - pre-commit>=2.7.1
  - qrcode=8.0
  - pip:
      - WeasyPrint>=52.2
