name: field-maps-scripts
channels:
  - Esri
  - conda-forge
dependencies:
  - arcgis=2.4.*
  - cairo>=1.16.0
  - jinja2>=2.11.2
  - pango>=1.42.4
  - pip>=19.1.1
  - python>=3.10.0
  - flake8>=3.8.3
  - pre-commit>=2.7.1
  - qrcode>=6.1
  - WeasyPrint>=52.2
  - pip:
      - pyproj==3.7.0
      - cartopy>=0.18.0
